# Generated by Django 4.0.4 on 2022-05-09 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUniversidad', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrera',
            old_name='Carrera',
            new_name='NombreCarrera',
        ),
    ]
